### PR TITLE
feat: Prevent the creation of constant delay schedules that are not a multiple of one second.

### LINKED ISSUE #21: Do not allow durations with fractions of a sec
Hi everyone,

I just noticed some slightly confusing behaviour for sub-second intervals:
If you start a job with `@every 1ms` it will run every second, if you start it with `@every 1s999ms` it will run every second as well. This seems to be intended behaviour but according to https://github.com/robfig/cron/issues/401 it's not worth implementing anything below one second.

Do you think it might be a good idea to return an error instead of rounding to a full second? It's quite tempting to use milliseconds in unit tests.

Cheers :)

### PR DESCRIPTION
**Pull request by stubents**
As this is not supported anyway by this library it might lead to confusing behaviour

closes #21

### CODE REVIEW

**Comment by janrnc** [comment]
Hi @stubents, sorry for getting back to you just now that you have already worked on this.

In my opinion `ConstantDelaySchedule`, as an alternative implementation of the `Schedule` interface, should not necessarily suffer from this one second as minimum unit problem, even though I agree with your first assumption about this use case not being very appropriate.

Considering that its logic is contained in the single line return statement of the `Next()` method, I think similar schedules can be implemented externally case by case. How would you feel about making both the struct and methods private? This way we could handle the error directly in the existing function, without having to deal with the unhandy usage [you mentioned](https://github.com/gdgvda/cron/issues/21#issuecomment-2162278484).

**Comment by stubents** [comment]
Hi @janrnc, no worries and thanks for the feedback!

I'm not quite sure if I got you right. You'd like to create another `Schedule` implementation that is private and only used by the parser?

**Comment by janrnc** [comment]
Not exactly. The idea is to make the `ConstantDelaySchedule` struct and `Every()` func private. By doing so, the way we handle the error becomes much less important because it would be just an internal component. The private `every()` could handle the error itself, without requiring a dedicated function as the `MustEvery()` you're introducing. What do you think?

**Comment by stubents** [comment]
Makes sense, actually I think there's no good reason not to use the `@every` string anyway. I'll change the PR

**Review by janrnc — APPROVED** [review]
@stubents thank you for your contribution!

**Pull request merged**
